apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
 selector:
    matchLabels:
      app: echo-pod
 ports:
   - name: endpoint
     protocol: TCP
     port: 80
     targetPort: 8080
 type: LoadBalancer