apiVersion: v1
kind: Service
metadata:
  name: management-ui
  namespace: management-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9001
  selector:
    role: management-ui
  sessionAffinity: None
  type: LoadBalancer